# Generated by Django 5.1.6 on 2025-02-26 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_remove_spot_image_spotimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='coordinates',
            field=models.JSONField(help_text='Enter a list of [lat, lng] pairs'),
        ),
        migrations.AddField(
            model_name='spot',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spots', to='tourism.category'),
        ),
    ]
